/* ============================================================
 *  성과평가 프로세스 마인드맵 데이터 (v5 — Miro 재현)
 *  출처: '성과평가 프로세스' Miro 마인드맵 (mindmap 1~8.png)
 *  생성: process_json/build_miro.py
 *
 *  group(색상) = 깊이별 type / layer(필터축) = 대분류 브랜치
 * ============================================================ */

const GROUPS = {
  core:      { label: "중심", color: "#1f2937" },
  process:   { label: "대분류", color: "#356CB5" },
  phase:     { label: "단계", color: "#7c3aed" },
  concept:   { label: "항목", color: "#0891b2" },
  activity:  { label: "세부", color: "#2563eb" },
  task:      { label: "내용", color: "#4f46e5" },
};

/* 브랜치(대분류) 색상 = 노드 테두리·연결선·Layer 필터칩·범례 공통 (노드 배경은 밝은 tint) */
const LAYER_COLORS = {
  core:      "#334155",
  okr:       "#2563EB",
  mbo:       "#7C3AED",
  align:     "#E11D48",
  change:    "#EA580C",
  link:      "#0D9488",
  u1:        "#16A34A",
  u2:        "#0EA5E9",
  u3:        "#CA8A04",
  u4:        "#DB2777",
};

const TPL_UNIFIED_NODES = [
  { id: "root", group: "core", layer: "core", label: "HR 성과관리 프로세스 (MBO+OKR 통합)",
    summary: "HR 성과관리 프로세스 (MBO+OKR 통합)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n1", group: "process", layer: "okr", label: "OKR 핵심개념",
    summary: "OKR 핵심개념",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n2", group: "phase", layer: "okr", label: "Objective (목표)",
    summary: "Objective (목표)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n3", group: "concept", layer: "okr", label: "성취하고자 하는 것의 표현",
    summary: "성취하고자 하는 것의 표현",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n4", group: "concept", layer: "okr", label: "간결하고 영감을 주며 도전적",
    summary: "간결하고 영감을 주며 도전적",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n5", group: "concept", layer: "okr", label: "일상적·안정 목표가 아닌 새로 만들고 구축하는 목표",
    summary: "일상적·안정 목표가 아닌 새로 만들고 구축하는 목표",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n6", group: "concept", layer: "okr", label: "아무도 못 본 새로운 목표 지향",
    summary: "아무도 못 본 새로운 목표 지향",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n7", group: "phase", layer: "okr", label: "Key Result (핵심결과)",
    summary: "Key Result (핵심결과)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n8", group: "concept", layer: "okr", label: "목표 진행 과정 측정하는 결과 지표",
    summary: "목표 진행 과정 측정하는 결과 지표",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n9", group: "concept", layer: "okr", label: "목표별 2~5개 설정",
    summary: "목표별 2~5개 설정",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n10", group: "concept", layer: "okr", label: "양적·측정 가능한 지표",
    summary: "양적·측정 가능한 지표",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n11", group: "concept", layer: "okr", label: "Baseline 지표",
    summary: "Baseline 지표",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n12", group: "concept", layer: "okr", label: "Positive Metric 지표",
    summary: "Positive Metric 지표",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n13", group: "concept", layer: "okr", label: "Negative Metric 지표",
    summary: "Negative Metric 지표",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n14", group: "concept", layer: "okr", label: "Milestone 지표",
    summary: "Milestone 지표",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n15", group: "phase", layer: "okr", label: "FAST 핵심원칙",
    summary: "FAST 핵심원칙",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n16", group: "concept", layer: "okr", label: "Focus: 집중과 전념 3-5개 목표에 집중",
    summary: "Focus: 집중과 전념 3-5개 목표에 집중",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n17", group: "concept", layer: "okr", label: "Align: 정렬과 연결 투명함 전제 개인 업무와 조직 비전 정렬",
    summary: "Align: 정렬과 연결 투명함 전제 개인 업무와 조직 비전 정렬",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n18", group: "concept", layer: "okr", label: "Stretch: 도전적 목표 한계 뛰어넘는 높은 목표 구축",
    summary: "Stretch: 도전적 목표 한계 뛰어넘는 높은 목표 구축",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n19", group: "concept", layer: "okr", label: "Track & Update: 목표·핵심결과 지속 추적 및 지속/보완/시작/중단 변용",
    summary: "Track & Update: 목표·핵심결과 지속 추적 및 지속/보완/시작/중단 변용",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n20", group: "phase", layer: "okr", label: "Initiative",
    summary: "Initiative",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n21", group: "concept", layer: "okr", label: "핵심결과 달성 위한 통제 가능한 행동 지표",
    summary: "핵심결과 달성 위한 통제 가능한 행동 지표",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n22", group: "concept", layer: "okr", label: "가설 세우고 즉시 실행",
    summary: "가설 세우고 즉시 실행",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n23", group: "concept", layer: "okr", label: "상위 목표와 연계된 실행 수단",
    summary: "상위 목표와 연계된 실행 수단",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n24", group: "phase", layer: "okr", label: "CFR 요소",
    summary: "CFR 요소",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n25", group: "concept", layer: "okr", label: "Conversation: 구성원 간 대화 목표 공감 팀원과 리더 공유·정렬",
    summary: "Conversation: 구성원 간 대화 목표 공감 팀원과 리더 공유·정렬",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n26", group: "concept", layer: "okr", label: "Feedback: 양방향 결과·과정 피드백 네트워크 형태",
    summary: "Feedback: 양방향 결과·과정 피드백 네트워크 형태",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n27", group: "concept", layer: "okr", label: "Recognition: 작은 성취 인정 정례화 공유·북돋움",
    summary: "Recognition: 작은 성취 인정 정례화 공유·북돋움",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n28", group: "process", layer: "mbo", label: "MBO 핵심개념",
    summary: "MBO 핵심개념",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n29", group: "phase", layer: "mbo", label: "전통적 MBO 한계",
    summary: "전통적 MBO 한계",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n30", group: "concept", layer: "mbo", label: "Top-down 목표관리 연단위 경직 목표",
    summary: "Top-down 목표관리 연단위 경직 목표",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n31", group: "concept", layer: "mbo", label: "과거·결과 중심 평가",
    summary: "과거·결과 중심 평가",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n32", group: "concept", layer: "mbo", label: "형식적 프로세스 운영",
    summary: "형식적 프로세스 운영",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n33", group: "concept", layer: "mbo", label: "평가보상 도구화 문제",
    summary: "평가보상 도구화 문제",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n34", group: "phase", layer: "mbo", label: "성과관리 History",
    summary: "성과관리 History",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n35", group: "concept", layer: "mbo", label: "테일러리즘·포디즘의 생산성 관리 기반",
    summary: "테일러리즘·포디즘의 생산성 관리 기반",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n36", group: "concept", layer: "mbo", label: "테일러리즘에서 MBO로 진화",
    summary: "테일러리즘에서 MBO로 진화",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n37", group: "concept", layer: "mbo", label: "포디즘의 생산성 관리 방식",
    summary: "포디즘의 생산성 관리 방식",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n38", group: "concept", layer: "mbo", label: "연단위 경직 목표관리 체계",
    summary: "연단위 경직 목표관리 체계",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n39", group: "phase", layer: "mbo", label: "New Rules 전환",
    summary: "New Rules 전환",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n40", group: "concept", layer: "mbo", label: "연1회→상시 피드백으로 전환",
    summary: "연1회→상시 피드백으로 전환",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n41", group: "concept", layer: "mbo", label: "개인성과→조직성과 중심으로 전환",
    summary: "개인성과→조직성과 중심으로 전환",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n42", group: "concept", layer: "mbo", label: "비공개→공개 방식으로 전환",
    summary: "비공개→공개 방식으로 전환",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n43", group: "concept", layer: "mbo", label: "Top-down→Bottom-up 방향 전환",
    summary: "Top-down→Bottom-up 방향 전환",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n44", group: "concept", layer: "mbo", label: "평가연계→간접연계 방식으로 전환",
    summary: "평가연계→간접연계 방식으로 전환",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n45", group: "phase", layer: "mbo", label: "MBO 프로세스",
    summary: "MBO 프로세스",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n46", group: "concept", layer: "mbo", label: "목표수립 2-3월 시작",
    summary: "목표수립 2-3월 시작",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n47", group: "concept", layer: "mbo", label: "Mid-year Review 7월 중간점검",
    summary: "Mid-year Review 7월 중간점검",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n48", group: "concept", layer: "mbo", label: "평가 12-1월 연말 평가",
    summary: "평가 12-1월 연말 평가",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n49", group: "concept", layer: "mbo", label: "Feedback 1월 결과 공유",
    summary: "Feedback 1월 결과 공유",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n50", group: "process", layer: "align", label: "X1 정렬·연계 (Alignment)",
    summary: "X1 정렬·연계 (Alignment)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n51", group: "phase", layer: "align", label: "OKR vs MBO 차이",
    summary: "OKR vs MBO 차이",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n52", group: "concept", layer: "align", label: "MBO 기계적 Cascading·할당 방식",
    summary: "MBO 기계적 Cascading·할당 방식",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n53", group: "concept", layer: "align", label: "OKR 상위 목표 기여 기반 유연한 연계",
    summary: "OKR 상위 목표 기여 기반 유연한 연계",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n54", group: "concept", layer: "align", label: "상위 목표로 하위로 기계적 Cascade 지양",
    summary: "상위 목표로 하위로 기계적 Cascade 지양",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n55", group: "phase", layer: "align", label: "수직적 Alignment",
    summary: "수직적 Alignment",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n56", group: "concept", layer: "align", label: "Top-Down 방향성·의미 정렬",
    summary: "Top-Down 방향성·의미 정렬",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n57", group: "concept", layer: "align", label: "Bottom-Up 기여 기반 자율 수립",
    summary: "Bottom-Up 기여 기반 자율 수립",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n58", group: "concept", layer: "align", label: "상위조직과 하위조직 간 균형",
    summary: "상위조직과 하위조직 간 균형",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n59", group: "phase", layer: "align", label: "수평적 Alignment",
    summary: "수평적 Alignment",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n60", group: "concept", layer: "align", label: "수평 조직 간 우선순위 논의",
    summary: "수평 조직 간 우선순위 논의",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n61", group: "concept", layer: "align", label: "기능적 연결·협업 강화",
    summary: "기능적 연결·협업 강화",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n62", group: "concept", layer: "align", label: "조직 수평 조직 간 정렬",
    summary: "조직 수평 조직 간 정렬",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n63", group: "phase", layer: "align", label: "Core OKR",
    summary: "Core OKR",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n64", group: "concept", layer: "align", label: "재무 성과 직접 창출·기여",
    summary: "재무 성과 직접 창출·기여",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n65", group: "concept", layer: "align", label: "직접적 Alignment 방식",
    summary: "직접적 Alignment 방식",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n66", group: "concept", layer: "align", label: "상위 성과지표 직접 기여 검토",
    summary: "상위 성과지표 직접 기여 검토",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n67", group: "phase", layer: "align", label: "Support OKR",
    summary: "Support OKR",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n68", group: "concept", layer: "align", label: "간접 기여·지원 조직",
    summary: "간접 기여·지원 조직",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n69", group: "concept", layer: "align", label: "간접적 Alignment 방식",
    summary: "간접적 Alignment 방식",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n70", group: "concept", layer: "align", label: "상위 OKR에 간접 기여 방식·충돌 여부 검토",
    summary: "상위 OKR에 간접 기여 방식·충돌 여부 검토",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n71", group: "phase", layer: "align", label: "Alignment Workshop",
    summary: "Alignment Workshop",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n72", group: "concept", layer: "align", label: "조직 간 OKR 적합성·연계성 검토",
    summary: "조직 간 OKR 적합성·연계성 검토",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n73", group: "concept", layer: "align", label: "우선순위 수립 및 결정",
    summary: "우선순위 수립 및 결정",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n74", group: "concept", layer: "align", label: "인적·물적 자원 배분 결정",
    summary: "인적·물적 자원 배분 결정",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n75", group: "concept", layer: "align", label: "경영진/OKR Champion 조직별 Alignment 주도",
    summary: "경영진/OKR Champion 조직별 Alignment 주도",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n76", group: "process", layer: "change", label: "X2 변화관리·원칙·문화",
    summary: "X2 변화관리·원칙·문화",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n77", group: "phase", layer: "change", label: "변화관리 전략 3단계",
    summary: "변화관리 전략 3단계",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n78", group: "concept", layer: "change", label: "Step1 변화 가치 정의",
    summary: "Step1 변화 가치 정의",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n79", group: "concept", layer: "change", label: "Step2 소규모 적용·촉진",
    summary: "Step2 소규모 적용·촉진",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n80", group: "concept", layer: "change", label: "Step3 전파·확장 정착",
    summary: "Step3 전파·확장 정착",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n81", group: "phase", layer: "change", label: "6대 행동강령",
    summary: "6대 행동강령",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n82", group: "concept", layer: "change", label: "성장 마인드 기르기 Growth Mindset 콘테스트",
    summary: "성장 마인드 기르기 Growth Mindset 콘테스트",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n83", group: "concept", layer: "change", label: "좋은 질문하기 What·How 열린 질문",
    summary: "좋은 질문하기 What·How 열린 질문",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n84", group: "concept", layer: "change", label: "OKR 공유하기 전 과정 시스템 공개",
    summary: "OKR 공유하기 전 과정 시스템 공개",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n85", group: "concept", layer: "change", label: "Alignment 연습 Transparency 미팅",
    summary: "Alignment 연습 Transparency 미팅",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n86", group: "concept", layer: "change", label: "책임 주기 설정 Daily/Weekly/Monthly/Quarterly Cadence",
    summary: "책임 주기 설정 Daily/Weekly/Monthly/Quarterly Cadence",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n87", group: "concept", layer: "change", label: "AD-FIT 코칭 Assess·Define·Focus·Implement·Take-away",
    summary: "AD-FIT 코칭 Assess·Define·Focus·Implement·Take-away",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n88", group: "phase", layer: "change", label: "역할 정의",
    summary: "역할 정의",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n89", group: "concept", layer: "change", label: "팀원 OKR 담당자 수립·실행·측정·회고",
    summary: "팀원 OKR 담당자 수립·실행·측정·회고",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n90", group: "concept", layer: "change", label: "팀장 OKR 관리자 논의·정렬·코칭·피드백",
    summary: "팀장 OKR 관리자 논의·정렬·코칭·피드백",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n91", group: "concept", layer: "change", label: "OKR Champion 상위 조직별 책임자",
    summary: "OKR Champion 상위 조직별 책임자",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n92", group: "concept", layer: "change", label: "임원/CEO 변화 의지·전략 공유·자원 배분·정렬 주도",
    summary: "임원/CEO 변화 의지·전략 공유·자원 배분·정렬 주도",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n93", group: "phase", layer: "change", label: "OKR 도입 원칙",
    summary: "OKR 도입 원칙",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n94", group: "concept", layer: "change", label: "진정한 OKR 아무도 못 본 새로운 목표",
    summary: "진정한 OKR 아무도 못 본 새로운 목표",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n95", group: "concept", layer: "change", label: "집중·우선순위 높은 3-5개 목표에 집중",
    summary: "집중·우선순위 높은 3-5개 목표에 집중",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n96", group: "concept", layer: "change", label: "투명성 기반 조직 전체 공개 운영",
    summary: "투명성 기반 조직 전체 공개 운영",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n97", group: "process", layer: "link", label: "성과평가 연계",
    summary: "성과평가 연계",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n98", group: "phase", layer: "link", label: "OKR 활용 평가",
    summary: "OKR 활용 평가",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n99", group: "concept", layer: "link", label: "결과 직접 평가 벗어나 목표 의미·과정 종합 판단",
    summary: "결과 직접 평가 벗어나 목표 의미·과정 종합 판단",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n100", group: "concept", layer: "link", label: "다각적 논의로 평가·보상 연계",
    summary: "다각적 논의로 평가·보상 연계",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n101", group: "concept", layer: "link", label: "목표 난이도·환경·내부 이슈 종합 고려",
    summary: "목표 난이도·환경·내부 이슈 종합 고려",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n102", group: "phase", layer: "link", label: "종합 리뷰 프로세스",
    summary: "종합 리뷰 프로세스",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n103", group: "concept", layer: "link", label: "목표·360 피드백·배지 통해 성과 종합 리뷰",
    summary: "목표·360 피드백·배지 통해 성과 종합 리뷰",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n104", group: "concept", layer: "link", label: "성과 내용·난이도·달성 과정 종합",
    summary: "성과 내용·난이도·달성 과정 종합",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n105", group: "concept", layer: "link", label: "역량 실천 종합 리뷰",
    summary: "역량 실천 종합 리뷰",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n106", group: "concept", layer: "link", label: "종합 리뷰→인재 스냅샷→인재 논의 순서",
    summary: "종합 리뷰→인재 스냅샷→인재 논의 순서",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n107", group: "phase", layer: "link", label: "인재 스냅샷",
    summary: "인재 스냅샷",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n108", group: "concept", layer: "link", label: "성과·역량·승진가능성 기록",
    summary: "성과·역량·승진가능성 기록",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n109", group: "concept", layer: "link", label: "이직위험·보상·저성과 이슈 기록",
    summary: "이직위험·보상·저성과 이슈 기록",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n110", group: "concept", layer: "link", label: "블록·종합등급 구성원 종합 기록",
    summary: "블록·종합등급 구성원 종합 기록",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n111", group: "phase", layer: "link", label: "Talent Session",
    summary: "Talent Session",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n112", group: "concept", layer: "link", label: "성과·보상·육성·인재관리 역량 논의",
    summary: "성과·보상·육성·인재관리 역량 논의",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n113", group: "concept", layer: "link", label: "평가 결과 객관성·공정성 제고",
    summary: "평가 결과 객관성·공정성 제고",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n114", group: "concept", layer: "link", label: "조직 인재 포트폴리오 관리",
    summary: "조직 인재 포트폴리오 관리",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n115", group: "phase", layer: "link", label: "MBO 평가 프로세스",
    summary: "MBO 평가 프로세스",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n116", group: "concept", layer: "link", label: "KPI 항목별 실적 집계",
    summary: "KPI 항목별 실적 집계",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n117", group: "concept", layer: "link", label: "자기평가 실시",
    summary: "자기평가 실시",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n118", group: "concept", layer: "link", label: "상사평가 실시",
    summary: "상사평가 실시",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n119", group: "concept", layer: "link", label: "Calibration 차상위자 Review·조정",
    summary: "Calibration 차상위자 Review·조정",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n120", group: "concept", layer: "link", label: "등급 확정·보고",
    summary: "등급 확정·보고",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n121", group: "phase", layer: "link", label: "MBO-OKR 통합 연계 포인트",
    summary: "MBO-OKR 통합 연계 포인트",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n122", group: "concept", layer: "link", label: "OKR 과정 데이터 MBO 평가 인풋으로 활용",
    summary: "OKR 과정 데이터 MBO 평가 인풋으로 활용",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n123", group: "concept", layer: "link", label: "정성적 과정 평가와 정량적 KPI 병행",
    summary: "정성적 과정 평가와 정량적 KPI 병행",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n124", group: "concept", layer: "link", label: "상시 피드백으로 연말 평가 부담 경감",
    summary: "상시 피드백으로 연말 평가 부담 경감",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n125", group: "process", layer: "u1", label: "U1 목표수립 (Define)",
    summary: "U1 목표수립 (Define)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n126", group: "phase", layer: "u1", label: "목표 Pool 작성 및 우선순위화",
    summary: "목표 Pool 작성 및 우선순위화",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n127", group: "concept", layer: "u1", label: "5-7개 목표 Brainstorming",
    summary: "5-7개 목표 Brainstorming",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n128", group: "concept", layer: "u1", label: "우선순위 3-5개로 압축",
    summary: "우선순위 3-5개로 압축",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n129", group: "concept", layer: "u1", label: "우선상위·협력 팀원 논의",
    summary: "우선상위·협력 팀원 논의",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n130", group: "phase", layer: "u1", label: "핵심결과 Pool 작성 및 우선순위화",
    summary: "핵심결과 Pool 작성 및 우선순위화",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n131", group: "concept", layer: "u1", label: "목표별 달팀원 팀장 최종 목표 확인",
    summary: "목표별 달팀원 팀장 최종 목표 확인",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n132", group: "concept", layer: "u1", label: "영향력과 팀원 팀장 핵심결과 도출",
    summary: "영향력과 팀원 팀장 핵심결과 도출",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n133", group: "concept", layer: "u1", label: "목표별 3-5개 핵심결과 확정",
    summary: "목표별 3-5개 핵심결과 확정",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n134", group: "phase", layer: "u1", label: "개인 KPI·목표수준·가중치 설정",
    summary: "개인 KPI·목표수준·가중치 설정",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n135", group: "concept", layer: "u1", label: "FAST 원칙 기반 개인 OKR 확정",
    summary: "FAST 원칙 기반 개인 OKR 확정",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n136", group: "concept", layer: "u1", label: "Initiative 상위 목표 연계 실행 수단 수립",
    summary: "Initiative 상위 목표 연계 실행 수단 수립",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n137", group: "concept", layer: "u1", label: "Performance 성과관리 팀원 팀장 연계 확인",
    summary: "Performance 성과관리 팀원 팀장 연계 확인",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n138", group: "phase", layer: "u1", label: "목표 검토 회의 및 확정",
    summary: "목표 검토 회의 및 확정",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n139", group: "concept", layer: "u1", label: "데이터 주기 시작일 설정",
    summary: "데이터 주기 시작일 설정",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n140", group: "concept", layer: "u1", label: "공유 범위 전사 공유 또는 조직 내 설정",
    summary: "공유 범위 전사 공유 또는 조직 내 설정",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n141", group: "concept", layer: "u1", label: "OKR 측정 진행률 지속 측정할 지표 설정",
    summary: "OKR 측정 진행률 지속 측정할 지표 설정",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n142", group: "phase", layer: "u1", label: "OKR Canvas 활용 Brainstorming",
    summary: "OKR Canvas 활용 Brainstorming",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n143", group: "concept", layer: "u1", label: "전사 Mission 공유 및 조직 방향성 확인",
    summary: "전사 Mission 공유 및 조직 방향성 확인",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n144", group: "concept", layer: "u1", label: "팀원 담당 1시간 이내 전사 및 조직 OKR 이해",
    summary: "팀원 담당 1시간 이내 전사 및 조직 OKR 이해",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n145", group: "concept", layer: "u1", label: "팀장 OKR Canvas 목표·핵심결과 공유",
    summary: "팀장 OKR Canvas 목표·핵심결과 공유",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n146", group: "process", layer: "u2", label: "U2 실행·점검 (Execute & Measure)",
    summary: "U2 실행·점검 (Execute & Measure)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n147", group: "phase", layer: "u2", label: "측정 Measuring",
    summary: "측정 Measuring",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n148", group: "concept", layer: "u2", label: "OKR 진행 과정 기록·측정",
    summary: "OKR 진행 과정 기록·측정",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n149", group: "concept", layer: "u2", label: "각 KR로 목표 진행 수준 산출",
    summary: "각 KR로 목표 진행 수준 산출",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n150", group: "concept", layer: "u2", label: "자기 점검 및 승인",
    summary: "자기 점검 및 승인",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n151", group: "phase", layer: "u2", label: "리뷰 Reviewing",
    summary: "리뷰 Reviewing",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n152", group: "concept", layer: "u2", label: "주간 브리핑 (목표 점검·회고)",
    summary: "주간 브리핑 (목표 점검·회고)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n153", group: "activity", layer: "u2", label: "미팅 사전 준비 Scrum",
    summary: "미팅 사전 준비 Scrum",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n154", group: "activity", layer: "u2", label: "목표점검 Agenda (진척도·핵심결과·지원요청)",
    summary: "목표점검 Agenda (진척도·핵심결과·지원요청)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n155", group: "activity", layer: "u2", label: "회고 문항 Follow Up (보완·중단·지속 결정)",
    summary: "회고 문항 Follow Up (보완·중단·지속 결정)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n156", group: "concept", layer: "u2", label: "KPTA 검토법 (Keep·Try·Problem·Action)",
    summary: "KPTA 검토법 (Keep·Try·Problem·Action)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n157", group: "concept", layer: "u2", label: "Kanban 운영 (To Do·Doing·Done)",
    summary: "Kanban 운영 (To Do·Doing·Done)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n158", group: "phase", layer: "u2", label: "추적·개선 Track & Update",
    summary: "추적·개선 Track & Update",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n159", group: "concept", layer: "u2", label: "OKR 달성도 종합리뷰",
    summary: "OKR 달성도 종합리뷰",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n160", group: "activity", layer: "u2", label: "개인 종합 리뷰 (FAST 원칙별 검증)",
    summary: "개인 종합 리뷰 (FAST 원칙별 검증)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n161", group: "activity", layer: "u2", label: "상위관리자 리뷰 (CFR 종합)",
    summary: "상위관리자 리뷰 (CFR 종합)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n162", group: "activity", layer: "u2", label: "OKR 지향노트 (차기 OKR 정교화)",
    summary: "OKR 지향노트 (차기 OKR 정교화)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n163", group: "concept", layer: "u2", label: "Next OKR 개선방안 (지속·보완·중단 결정)",
    summary: "Next OKR 개선방안 (지속·보완·중단 결정)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n164", group: "phase", layer: "u2", label: "Mid-year Review 중간점검",
    summary: "Mid-year Review 중간점검",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n165", group: "concept", layer: "u2", label: "Mid-year Review 준비",
    summary: "Mid-year Review 준비",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n166", group: "activity", layer: "u2", label: "Review 일정·Guide 수립",
    summary: "Review 일정·Guide 수립",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n167", group: "activity", layer: "u2", label: "본인 중간점검 양식 작성",
    summary: "본인 중간점검 양식 작성",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n168", group: "activity", layer: "u2", label: "달성도 사전 점검·면담 일정 Arrange",
    summary: "달성도 사전 점검·면담 일정 Arrange",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n169", group: "activity", layer: "u2", label: "본인 중간 점검 Template",
    summary: "본인 중간 점검 Template",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n170", group: "concept", layer: "u2", label: "중간 점검 면담",
    summary: "중간 점검 면담",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n171", group: "activity", layer: "u2", label: "1:1 중간 점검 면담 실시",
    summary: "1:1 중간 점검 면담 실시",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n172", group: "activity", layer: "u2", label: "면담 참관·진행 현황 Monitoring",
    summary: "면담 참관·진행 현황 Monitoring",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n173", group: "concept", layer: "u2", label: "결과 정리·취합",
    summary: "결과 정리·취합",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n174", group: "activity", layer: "u2", label: "면담 결과 정리·송부",
    summary: "면담 결과 정리·송부",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n175", group: "activity", layer: "u2", label: "결과 취합·보고 (BG장/CEO)",
    summary: "결과 취합·보고 (BG장/CEO)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n176", group: "activity", layer: "u2", label: "Mid-year Review 결과 정리 Template",
    summary: "Mid-year Review 결과 정리 Template",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n177", group: "concept", layer: "u2", label: "Check Point 점검",
    summary: "Check Point 점검",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n178", group: "activity", layer: "u2", label: "Check A: 역할·책임 변화 (R&R)",
    summary: "Check A: 역할·책임 변화 (R&R)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n179", group: "activity", layer: "u2", label: "Check B: 목표 진척도 (Progress)",
    summary: "Check B: 목표 진척도 (Progress)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n180", group: "activity", layer: "u2", label: "Intervention 개입",
    summary: "Intervention 개입",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n181", group: "concept", layer: "u2", label: "면담 진행 Checklist",
    summary: "면담 진행 Checklist",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n182", group: "activity", layer: "u2", label: "Process 측면 점검",
    summary: "Process 측면 점검",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n183", group: "activity", layer: "u2", label: "Contents 측면 (목표 달성도) 점검",
    summary: "Contents 측면 (목표 달성도) 점검",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n184", group: "concept", layer: "u2", label: "STAR 기법 (Situation·Task·Action·Result)",
    summary: "STAR 기법 (Situation·Task·Action·Result)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n185", group: "process", layer: "u3", label: "U3 평가 (Review)",
    summary: "U3 평가 (Review)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n186", group: "phase", layer: "u3", label: "OKR 활용 (성과 평가)",
    summary: "OKR 활용 (성과 평가)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n187", group: "concept", layer: "u3", label: "성과 평가의 변화 (개선·발전 리뷰)",
    summary: "성과 평가의 변화 (개선·발전 리뷰)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n188", group: "concept", layer: "u3", label: "OKR 활용 프로세스",
    summary: "OKR 활용 프로세스",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n189", group: "activity", layer: "u3", label: "종합 리뷰",
    summary: "종합 리뷰",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n190", group: "task", layer: "u3", label: "360 피드백",
    summary: "360 피드백",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n191", group: "task", layer: "u3", label: "배지 (인정·피드백)",
    summary: "배지 (인정·피드백)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n192", group: "activity", layer: "u3", label: "성과의 해석 (난이도·환경·내부 이슈)",
    summary: "성과의 해석 (난이도·환경·내부 이슈)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n193", group: "activity", layer: "u3", label: "인재 스냅샷",
    summary: "인재 스냅샷",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n194", group: "activity", layer: "u3", label: "인재 스냅샷 자가진단 (평가 오류 점검)",
    summary: "인재 스냅샷 자가진단 (평가 오류 점검)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n195", group: "activity", layer: "u3", label: "인재 논의 Talent Session",
    summary: "인재 논의 Talent Session",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n196", group: "phase", layer: "u3", label: "평가 (KPI 점수·등급 산출)",
    summary: "평가 (KPI 점수·등급 산출)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n197", group: "concept", layer: "u3", label: "평가 지침 수립·안내",
    summary: "평가 지침 수립·안내",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n198", group: "activity", layer: "u3", label: "평가 운영 계획 수립·보고",
    summary: "평가 운영 계획 수립·보고",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n199", group: "activity", layer: "u3", label: "중역/팀장 평가 Guide 배포·Training",
    summary: "중역/팀장 평가 Guide 배포·Training",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n200", group: "concept", layer: "u3", label: "자기 평가",
    summary: "자기 평가",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n201", group: "activity", layer: "u3", label: "평가항목별 실적 자료 집계",
    summary: "평가항목별 실적 자료 집계",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n202", group: "activity", layer: "u3", label: "자기 평가서 작성",
    summary: "자기 평가서 작성",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n203", group: "activity", layer: "u3", label: "자기평가서 송부",
    summary: "자기평가서 송부",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n204", group: "activity", layer: "u3", label: "평가 Template",
    summary: "평가 Template",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n205", group: "concept", layer: "u3", label: "상사 평가",
    summary: "상사 평가",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n206", group: "activity", layer: "u3", label: "자기 평가 결과 검토",
    summary: "자기 평가 결과 검토",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n207", group: "activity", layer: "u3", label: "상사 평가 실시",
    summary: "상사 평가 실시",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n208", group: "activity", layer: "u3", label: "정성평가 근거 Template",
    summary: "정성평가 근거 Template",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n209", group: "concept", layer: "u3", label: "Calibration",
    summary: "Calibration",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n210", group: "activity", layer: "u3", label: "Calibration 준비",
    summary: "Calibration 준비",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n211", group: "activity", layer: "u3", label: "차상위자 평가 결과 Review",
    summary: "차상위자 평가 결과 Review",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n212", group: "activity", layer: "u3", label: "Calibration Meeting 실시",
    summary: "Calibration Meeting 실시",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n213", group: "activity", layer: "u3", label: "BG HR Review Report",
    summary: "BG HR Review Report",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n214", group: "concept", layer: "u3", label: "평가 결과 확정·보고",
    summary: "평가 결과 확정·보고",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n215", group: "activity", layer: "u3", label: "평가 점수 확정·등급 부여",
    summary: "평가 점수 확정·등급 부여",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n216", group: "activity", layer: "u3", label: "평가 결과 정리·보고",
    summary: "평가 결과 정리·보고",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n217", group: "activity", layer: "u3", label: "최종 평가 등급 확정 정리 양식",
    summary: "최종 평가 등급 확정 정리 양식",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n218", group: "concept", layer: "u3", label: "신규·이동·TF 평가 Guide",
    summary: "신규·이동·TF 평가 Guide",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n219", group: "activity", layer: "u3", label: "TF/Project 성과 반영 Process",
    summary: "TF/Project 성과 반영 Process",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n220", group: "task", layer: "u3", label: "주체별 역할 (피평가자·TF Mgr·팀장·HR)",
    summary: "주체별 역할 (피평가자·TF Mgr·팀장·HR)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n221", group: "task", layer: "u3", label: "TF/PRJ 평가점수 산출 (세부항목×가중치)",
    summary: "TF/PRJ 평가점수 산출 (세부항목×가중치)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n222", group: "concept", layer: "u3", label: "성과 Back-up Data 수집",
    summary: "성과 Back-up Data 수집",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n223", group: "activity", layer: "u3", label: "설명 항목",
    summary: "설명 항목",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n224", group: "activity", layer: "u3", label: "예시 항목",
    summary: "예시 항목",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n225", group: "concept", layer: "u3", label: "Calibration Point",
    summary: "Calibration Point",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n226", group: "activity", layer: "u3", label: "Calibration의 목적",
    summary: "Calibration의 목적",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n227", group: "activity", layer: "u3", label: "주요 검토 포인트 (관대화·중심화·가혹화)",
    summary: "주요 검토 포인트 (관대화·중심화·가혹화)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n228", group: "concept", layer: "u3", label: "HR 평가결과 분석",
    summary: "HR 평가결과 분석",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n229", group: "activity", layer: "u3", label: "전체 점수 분포 분석",
    summary: "전체 점수 분포 분석",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n230", group: "task", layer: "u3", label: "Dimension 구분 (직책×Category)",
    summary: "Dimension 구분 (직책×Category)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n231", group: "task", layer: "u3", label: "통계 지표 (평균·표준편차·첨도·편도)",
    summary: "통계 지표 (평균·표준편차·첨도·편도)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n232", group: "activity", layer: "u3", label: "조직별 비교 분석",
    summary: "조직별 비교 분석",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n233", group: "task", layer: "u3", label: "평균과의 Gap",
    summary: "평균과의 Gap",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n234", group: "activity", layer: "u3", label: "MBO Category별 비교 분석",
    summary: "MBO Category별 비교 분석",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n235", group: "task", layer: "u3", label: "Category별 총점 영향도",
    summary: "Category별 총점 영향도",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n236", group: "process", layer: "u4", label: "U4 피드백 (Feedback)",
    summary: "U4 피드백 (Feedback)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n237", group: "phase", layer: "u4", label: "CFR (Conversation·Feedback·Recognition)",
    summary: "CFR (Conversation·Feedback·Recognition)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n238", group: "concept", layer: "u4", label: "Conversation (구성원 간 대화)",
    summary: "Conversation (구성원 간 대화)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n239", group: "concept", layer: "u4", label: "Feedback (결과·과정 피드백)",
    summary: "Feedback (결과·과정 피드백)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n240", group: "concept", layer: "u4", label: "Recognition (성취에 대한 인정)",
    summary: "Recognition (성취에 대한 인정)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n241", group: "phase", layer: "u4", label: "Feedback (평가 결과 Feedback)",
    summary: "Feedback (평가 결과 Feedback)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n242", group: "concept", layer: "u4", label: "Feedback 준비",
    summary: "Feedback 준비",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n243", group: "activity", layer: "u4", label: "평가자 대상 Feedback 안내",
    summary: "평가자 대상 Feedback 안내",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n244", group: "activity", layer: "u4", label: "Feedback 면담 계획 수립",
    summary: "Feedback 면담 계획 수립",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n245", group: "activity", layer: "u4", label: "Feedback Note 작성",
    summary: "Feedback Note 작성",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n246", group: "task", layer: "u4", label: "Feedback Note (점수·등급·성과급·Comment)",
    summary: "Feedback Note (점수·등급·성과급·Comment)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n247", group: "concept", layer: "u4", label: "Feedback 실시",
    summary: "Feedback 실시",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n248", group: "activity", layer: "u4", label: "1:1 Feedback Meeting 실시",
    summary: "1:1 Feedback Meeting 실시",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n249", group: "activity", layer: "u4", label: "진행 현황 Monitoring",
    summary: "진행 현황 Monitoring",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n250", group: "concept", layer: "u4", label: "Feedback 결과 정리",
    summary: "Feedback 결과 정리",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n251", group: "activity", layer: "u4", label: "결과 정리·송부",
    summary: "결과 정리·송부",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n252", group: "activity", layer: "u4", label: "결과 취합·보고 (BG장/CEO)",
    summary: "결과 취합·보고 (BG장/CEO)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n253", group: "activity", layer: "u4", label: "Feedback Meeting 결과 정리 양식",
    summary: "Feedback Meeting 결과 정리 양식",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n254", group: "concept", layer: "u4", label: "Feedback Template",
    summary: "Feedback Template",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n255", group: "concept", layer: "u4", label: "효과적 Communication Tips (경청·질문·긍정언어)",
    summary: "효과적 Communication Tips (경청·질문·긍정언어)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n256", group: "concept", layer: "u4", label: "구성원 상황별 Feedback Point",
    summary: "구성원 상황별 Feedback Point",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n257", group: "activity", layer: "u4", label: "Positive Feedback (동기부여)",
    summary: "Positive Feedback (동기부여)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
  { id: "n258", group: "activity", layer: "u4", label: "Negative Feedback (성과 강화)",
    summary: "Negative Feedback (성과 강화)",
    detail: [], src: "성과평가 프로세스 (Miro)" },
];

const TPL_UNIFIED_EDGES = [
  { from: "root", to: "n1" },
  { from: "n1", to: "n2" },
  { from: "n2", to: "n3" },
  { from: "n2", to: "n4" },
  { from: "n2", to: "n5" },
  { from: "n2", to: "n6" },
  { from: "n1", to: "n7" },
  { from: "n7", to: "n8" },
  { from: "n7", to: "n9" },
  { from: "n7", to: "n10" },
  { from: "n7", to: "n11" },
  { from: "n7", to: "n12" },
  { from: "n7", to: "n13" },
  { from: "n7", to: "n14" },
  { from: "n1", to: "n15" },
  { from: "n15", to: "n16" },
  { from: "n15", to: "n17" },
  { from: "n15", to: "n18" },
  { from: "n15", to: "n19" },
  { from: "n1", to: "n20" },
  { from: "n20", to: "n21" },
  { from: "n20", to: "n22" },
  { from: "n20", to: "n23" },
  { from: "n1", to: "n24" },
  { from: "n24", to: "n25" },
  { from: "n24", to: "n26" },
  { from: "n24", to: "n27" },
  { from: "root", to: "n28" },
  { from: "n28", to: "n29" },
  { from: "n29", to: "n30" },
  { from: "n29", to: "n31" },
  { from: "n29", to: "n32" },
  { from: "n29", to: "n33" },
  { from: "n28", to: "n34" },
  { from: "n34", to: "n35" },
  { from: "n34", to: "n36" },
  { from: "n34", to: "n37" },
  { from: "n34", to: "n38" },
  { from: "n28", to: "n39" },
  { from: "n39", to: "n40" },
  { from: "n39", to: "n41" },
  { from: "n39", to: "n42" },
  { from: "n39", to: "n43" },
  { from: "n39", to: "n44" },
  { from: "n28", to: "n45" },
  { from: "n45", to: "n46" },
  { from: "n45", to: "n47" },
  { from: "n45", to: "n48" },
  { from: "n45", to: "n49" },
  { from: "root", to: "n50" },
  { from: "n50", to: "n51" },
  { from: "n51", to: "n52" },
  { from: "n51", to: "n53" },
  { from: "n51", to: "n54" },
  { from: "n50", to: "n55" },
  { from: "n55", to: "n56" },
  { from: "n55", to: "n57" },
  { from: "n55", to: "n58" },
  { from: "n50", to: "n59" },
  { from: "n59", to: "n60" },
  { from: "n59", to: "n61" },
  { from: "n59", to: "n62" },
  { from: "n50", to: "n63" },
  { from: "n63", to: "n64" },
  { from: "n63", to: "n65" },
  { from: "n63", to: "n66" },
  { from: "n50", to: "n67" },
  { from: "n67", to: "n68" },
  { from: "n67", to: "n69" },
  { from: "n67", to: "n70" },
  { from: "n50", to: "n71" },
  { from: "n71", to: "n72" },
  { from: "n71", to: "n73" },
  { from: "n71", to: "n74" },
  { from: "n71", to: "n75" },
  { from: "root", to: "n76" },
  { from: "n76", to: "n77" },
  { from: "n77", to: "n78" },
  { from: "n77", to: "n79" },
  { from: "n77", to: "n80" },
  { from: "n76", to: "n81" },
  { from: "n81", to: "n82" },
  { from: "n81", to: "n83" },
  { from: "n81", to: "n84" },
  { from: "n81", to: "n85" },
  { from: "n81", to: "n86" },
  { from: "n81", to: "n87" },
  { from: "n76", to: "n88" },
  { from: "n88", to: "n89" },
  { from: "n88", to: "n90" },
  { from: "n88", to: "n91" },
  { from: "n88", to: "n92" },
  { from: "n76", to: "n93" },
  { from: "n93", to: "n94" },
  { from: "n93", to: "n95" },
  { from: "n93", to: "n96" },
  { from: "root", to: "n97" },
  { from: "n97", to: "n98" },
  { from: "n98", to: "n99" },
  { from: "n98", to: "n100" },
  { from: "n98", to: "n101" },
  { from: "n97", to: "n102" },
  { from: "n102", to: "n103" },
  { from: "n102", to: "n104" },
  { from: "n102", to: "n105" },
  { from: "n102", to: "n106" },
  { from: "n97", to: "n107" },
  { from: "n107", to: "n108" },
  { from: "n107", to: "n109" },
  { from: "n107", to: "n110" },
  { from: "n97", to: "n111" },
  { from: "n111", to: "n112" },
  { from: "n111", to: "n113" },
  { from: "n111", to: "n114" },
  { from: "n97", to: "n115" },
  { from: "n115", to: "n116" },
  { from: "n115", to: "n117" },
  { from: "n115", to: "n118" },
  { from: "n115", to: "n119" },
  { from: "n115", to: "n120" },
  { from: "n97", to: "n121" },
  { from: "n121", to: "n122" },
  { from: "n121", to: "n123" },
  { from: "n121", to: "n124" },
  { from: "root", to: "n125" },
  { from: "n125", to: "n126" },
  { from: "n126", to: "n127" },
  { from: "n126", to: "n128" },
  { from: "n126", to: "n129" },
  { from: "n125", to: "n130" },
  { from: "n130", to: "n131" },
  { from: "n130", to: "n132" },
  { from: "n130", to: "n133" },
  { from: "n125", to: "n134" },
  { from: "n134", to: "n135" },
  { from: "n134", to: "n136" },
  { from: "n134", to: "n137" },
  { from: "n125", to: "n138" },
  { from: "n138", to: "n139" },
  { from: "n138", to: "n140" },
  { from: "n138", to: "n141" },
  { from: "n125", to: "n142" },
  { from: "n142", to: "n143" },
  { from: "n142", to: "n144" },
  { from: "n142", to: "n145" },
  { from: "root", to: "n146" },
  { from: "n146", to: "n147" },
  { from: "n147", to: "n148" },
  { from: "n147", to: "n149" },
  { from: "n147", to: "n150" },
  { from: "n146", to: "n151" },
  { from: "n151", to: "n152" },
  { from: "n152", to: "n153" },
  { from: "n152", to: "n154" },
  { from: "n152", to: "n155" },
  { from: "n151", to: "n156" },
  { from: "n151", to: "n157" },
  { from: "n146", to: "n158" },
  { from: "n158", to: "n159" },
  { from: "n159", to: "n160" },
  { from: "n159", to: "n161" },
  { from: "n159", to: "n162" },
  { from: "n158", to: "n163" },
  { from: "n146", to: "n164" },
  { from: "n164", to: "n165" },
  { from: "n165", to: "n166" },
  { from: "n165", to: "n167" },
  { from: "n165", to: "n168" },
  { from: "n165", to: "n169" },
  { from: "n164", to: "n170" },
  { from: "n170", to: "n171" },
  { from: "n170", to: "n172" },
  { from: "n164", to: "n173" },
  { from: "n173", to: "n174" },
  { from: "n173", to: "n175" },
  { from: "n173", to: "n176" },
  { from: "n164", to: "n177" },
  { from: "n177", to: "n178" },
  { from: "n177", to: "n179" },
  { from: "n177", to: "n180" },
  { from: "n164", to: "n181" },
  { from: "n181", to: "n182" },
  { from: "n181", to: "n183" },
  { from: "n164", to: "n184" },
  { from: "root", to: "n185" },
  { from: "n185", to: "n186" },
  { from: "n186", to: "n187" },
  { from: "n186", to: "n188" },
  { from: "n188", to: "n189" },
  { from: "n189", to: "n190" },
  { from: "n189", to: "n191" },
  { from: "n188", to: "n192" },
  { from: "n188", to: "n193" },
  { from: "n188", to: "n194" },
  { from: "n188", to: "n195" },
  { from: "n185", to: "n196" },
  { from: "n196", to: "n197" },
  { from: "n197", to: "n198" },
  { from: "n197", to: "n199" },
  { from: "n196", to: "n200" },
  { from: "n200", to: "n201" },
  { from: "n200", to: "n202" },
  { from: "n200", to: "n203" },
  { from: "n200", to: "n204" },
  { from: "n196", to: "n205" },
  { from: "n205", to: "n206" },
  { from: "n205", to: "n207" },
  { from: "n205", to: "n208" },
  { from: "n196", to: "n209" },
  { from: "n209", to: "n210" },
  { from: "n209", to: "n211" },
  { from: "n209", to: "n212" },
  { from: "n209", to: "n213" },
  { from: "n196", to: "n214" },
  { from: "n214", to: "n215" },
  { from: "n214", to: "n216" },
  { from: "n214", to: "n217" },
  { from: "n196", to: "n218" },
  { from: "n218", to: "n219" },
  { from: "n219", to: "n220" },
  { from: "n219", to: "n221" },
  { from: "n196", to: "n222" },
  { from: "n222", to: "n223" },
  { from: "n222", to: "n224" },
  { from: "n196", to: "n225" },
  { from: "n225", to: "n226" },
  { from: "n225", to: "n227" },
  { from: "n196", to: "n228" },
  { from: "n228", to: "n229" },
  { from: "n229", to: "n230" },
  { from: "n229", to: "n231" },
  { from: "n228", to: "n232" },
  { from: "n232", to: "n233" },
  { from: "n228", to: "n234" },
  { from: "n234", to: "n235" },
  { from: "root", to: "n236" },
  { from: "n236", to: "n237" },
  { from: "n237", to: "n238" },
  { from: "n237", to: "n239" },
  { from: "n237", to: "n240" },
  { from: "n236", to: "n241" },
  { from: "n241", to: "n242" },
  { from: "n242", to: "n243" },
  { from: "n242", to: "n244" },
  { from: "n242", to: "n245" },
  { from: "n245", to: "n246" },
  { from: "n241", to: "n247" },
  { from: "n247", to: "n248" },
  { from: "n247", to: "n249" },
  { from: "n241", to: "n250" },
  { from: "n250", to: "n251" },
  { from: "n250", to: "n252" },
  { from: "n250", to: "n253" },
  { from: "n241", to: "n254" },
  { from: "n241", to: "n255" },
  { from: "n241", to: "n256" },
  { from: "n256", to: "n257" },
  { from: "n256", to: "n258" },
];

const PROCESS_TEMPLATES = {
  unified: {
    name: "성과평가 프로세스 (MBO+OKR 통합)",
    desc: "OKR/MBO 핵심개념 + 정렬·연계 + 변화관리 + 성과평가 연계 + 통합 4단계(목표수립→실행·점검→평가→피드백).",
    layers: {
      core:    { label: "중심", color: "#334155" },
      okr:     { label: "OKR 핵심개념", color: "#2563EB" },
      mbo:     { label: "MBO 핵심개념", color: "#7C3AED" },
      align:   { label: "X1 정렬·연계", color: "#E11D48" },
      change:  { label: "X2 변화관리·문화", color: "#EA580C" },
      link:    { label: "성과평가 연계", color: "#0D9488" },
      u1:      { label: "U1 목표수립", color: "#16A34A" },
      u2:      { label: "U2 실행·점검", color: "#0EA5E9" },
      u3:      { label: "U3 평가", color: "#CA8A04" },
      u4:      { label: "U4 피드백", color: "#DB2777" },
    },
    groupLayer: { core: "core" },
    nodes: TPL_UNIFIED_NODES, edges: TPL_UNIFIED_EDGES
  }
};

const DEFAULT_TEMPLATE = "unified";

/* 하위 호환 전역 */
const NODES = PROCESS_TEMPLATES[DEFAULT_TEMPLATE].nodes;
const EDGES = PROCESS_TEMPLATES[DEFAULT_TEMPLATE].edges;
